export const moodMap = {
    // (x, y)
    // x = pleasantness
    // y = energy
    // Blue quadrant
    "Despairing": { pleasantness: -5, energy: -5 },
    "Despondent": { pleasantness: -5, energy: -4 },
    "Alienated": { pleasantness: -5, energy: -3 },
    "Pessimistic": { pleasantness: -5, energy: -2 },
    "Disgusted": { pleasantness: -5, energy: -1 },
    "Hopeless": { pleasantness: -4, energy: -5 },
    "Depressed": { pleasantness: -4, energy: -4 },
    "Miserable": { pleasantness: -4, energy: -3 },
    "Morose": { pleasantness: -4, energy: -2 },
    "Glum": { pleasantness: -4, energy: -1 },
    "Desolate": { pleasantness: -3, energy: -5 },
    "Sullen": { pleasantness: -3, energy: -4 },
    "Lonely": { pleasantness: -3, energy: -3 },
    "Discouraged": { pleasantness: -3, energy: -2 },
    "Disappointed": { pleasantness: -3, energy: -1 },
    "Spent": { pleasantness: -2, energy: -5 },
    "Exhausted": { pleasantness: -2, energy: -4 },
    "Disheartened": { pleasantness: -2, energy: -3 },
    "Sad": { pleasantness: -2, energy: -2 },
    "Down": { pleasantness: -2, energy: -1 },
    "Drained": { pleasantness: -1, energy: -5 },
    "Fatigued": { pleasantness: -1, energy: -4 },
    "Tired": { pleasantness: -1, energy: -3 },
    "Bored": { pleasantness: -1, energy: -2 },
    "Apathetic": { pleasantness: -1, energy: -1 },
    //Green quadrant
    "At ease": { pleasantness: 1, energy: -1 },
    "Calm": { pleasantness: 1, energy: -2 },
    "Relaxed": { pleasantness: 1, energy: -3 },
    "Mellow": { pleasantness: 1, energy: -4 },
    "Sleepy": { pleasantness: 1, energy: -5 },
    "Easygoing": { pleasantness: 2, energy: -1 },
    "Secure": { pleasantness: 2, energy: -2 },
    "Chill": { pleasantness: 2, energy: -3 },
    "Thoughtful": { pleasantness: 2, energy: -4 },
    "Complacent": { pleasantness: 2, energy: -5 },
    "Content": { pleasantness: 3, energy: -1 },
    "Satisfied": { pleasantness: 3, energy: -2 },
    "Restful": { pleasantness: 3, energy: -3 },
    "Peaceful": { pleasantness: 3, energy: -4 },
    "Tranquil": { pleasantness: 3, energy: -5 },
    "Loving": { pleasantness: 4, energy: -1 },
    "Grateful": { pleasantness: 4, energy: -2 },
    "Blessed": { pleasantness: 4, energy: -3 },
    "Comfortable": { pleasantness: 4, energy: -4 },
    "Cozy": { pleasantness: 4, energy: -5 },
    "Fulfilled": { pleasantness: 5, energy: -1 },
    "Touched": { pleasantness: 5, energy: -2 },
    "Balanced": { pleasantness: 5, energy: -3 },
    "Carefree": { pleasantness: 5, energy: -4 },
    "Serene": { pleasantness: 5, energy: -5 },
    //Red quadrant
    "Enraged": { pleasantness: -5, energy: 5 },
    "Livid": { pleasantness: -5, energy: 4 },
    "Fuming": { pleasantness: -5, energy: 3 },
    "Anxious": { pleasantness: -5, energy: 2 },
    "Repulsed": { pleasantness: -5, energy: 1 },
    "Panicked": { pleasantness: -4, energy: 5 },
    "Furious": { pleasantness: -4, energy: 4 },
    "Frightened": { pleasantness: -4, energy: 3 },
    "Apprehensive": { pleasantness: -4, energy: 2 },
    "Troubled": { pleasantness: -4, energy: 1 },
    "Stressed": { pleasantness: -3, energy: 5 },
    "Frustrated": { pleasantness: -3, energy: 4 },
    "Angry": { pleasantness: -3, energy: 3 },
    "Worried": { pleasantness: -3, energy: 2 },
    "Concerned": { pleasantness: -3, energy: 1 },
    "Jittery": { pleasantness: -2, energy: 5 },
    "Tense": { pleasantness: -2, energy: 4 },
    "Nervous": { pleasantness: -2, energy: 3 },
    "Irritated": { pleasantness: -2, energy: 2 },
    "Uneasy": { pleasantness: -2, energy: 1 },
    "Shocked": { pleasantness: -1, energy: 5 },
    "Stunned": { pleasantness: -1, energy: 4 },
    "Restless": { pleasantness: -1, energy: 3 },
    "Annoyed": { pleasantness: -1, energy: 2 },
    "Peeved": { pleasantness: -1, energy: 1 },
    // Yellow quadrant
    "Pleasant": { pleasantness: 1, energy: 1 },
    "Pleaseful": { pleasantness: 1, energy: 2 },
    "Energized": { pleasantness: 1, energy: 3 },
    "Hyper": { pleasantness: 1, energy: 4 },
    "Surprised": { pleasantness: 1, energy: 5 },
    "Joyful": { pleasantness: 2, energy: 1 },
    "Focused": { pleasantness: 2, energy: 2 },
    "Lively": { pleasantness: 2, energy: 3 },
    "Cheerful": { pleasantness: 2, energy: 4 },
    "Upbeat": { pleasantness: 2, energy: 5 },
    "Hopeful": { pleasantness: 3, energy: 1 },
    "Happy": { pleasantness: 3, energy: 2 },
    "Excited": { pleasantness: 3, energy: 3 },
    "Motivated": { pleasantness: 3, energy: 4 },
    "Festive": { pleasantness: 3, energy: 5 },
    "Playful": { pleasantness: 4, energy: 1 },
    "Proud": { pleasantness: 4, energy: 2 },
    "Optimistic": { pleasantness: 4, energy: 3 },
    "Inspired": { pleasantness: 4, energy: 4 },
    "Exhilarated": { pleasantness: 4, energy: 5 },
    "Blissful": { pleasantness: 5, energy: 1 },
    "Thrilled": { pleasantness: 5, energy: 2 },
    "Enthusiastic": { pleasantness: 5, energy: 3 },
    "Elated": { pleasantness: 5, energy: 4 },
    "Ecstatic": { pleasantness: 5, energy: 5 }
  };
  