export const profassessmentStates = {
    
    FirstSet:{
        Exploration: null,
        Exploration2: null,
        Exploration3: null,
        Exploration4: null,
        Exploration5: null,
        InsightBuilding: null,
        InsightBuilding2: null,
        InsightBuilding3: null,
        InsightBuilding4: null,
        InsightBuilding5: null,
        ActionStrategies: null,
        ActionStrategies2: null,
        ActionStrategies3: null,
        ActionStrategies4: null,
        ActionStrategies5: null,
        TherapeuticAlliance: null,
        TherapeuticAlliance2: null,
        TherapeuticAlliance3: null,
        TherapeuticAlliance4: null,
        TherapeuticAlliance5: null,
        CaseFormulation: null,
        CaseFormulation2: null,
        CaseFormulation3: null,
        CaseFormulation4: null,
        CaseFormulation5: null,
    },
    firstRadioOptions: [
        { id: '1', label: 'Not at all Confident', value: '0' }, 
        { id: '2', label: 'A little Confident', value: '1' },
        { id: '3', label: 'Somewhat Confident', value: '2' },
        { id: '4', label: 'Very Confident', value: '3' },
        { id: '5', label: 'Extremely Confident', value: '4' },
    ],  
}